pki:
  ca: |
    # PASTE THE CONTENTS OF CA.CRT REPLACING THIS LINE
  cert: |
    CHANGE_CRT
  key: |
    CHANGE_KEY

static_host_map:
  "192.168.100.1": ["### REPLACE WITH PUBLIC IP OF YOUR LIGHTHOUSE SERVER ###:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 4243

punchy: true
punch_back: true

relay:
  relays:
    - 192.168.100.1
  am_relay: false
  use_relays: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
